import "styled-components";

declare module "styled-components" {
  export interface DefaultTheme {
    breakpoints: {
      xs: string;
      xxl: string;
    };
    colors: {
      white: string;
      orange: string;
      almostBlack: string;
      smokyWhite1: string;
      smokyWhite2: string;
      smokyWhite3: string;
      black: string;
      black2: string;
      gray: string;
      gray2: string;
      gray3: string;
      gray4: string;
      gray5: string;
      gray6: string;
      gray7: string;
      gray8: string;
      gray9: string;
      gray10: string;
      gray11: string;
      gray12: string;
      gray13: string;
      gray14: string;
      gray15: string;
      gray16: string;
      gray17: string;
      gray18: string;
      gray19: string;
      gray20: string;
      gray21: string;
      gray22: string;
      lightCyan: string;
      gray23: string;
      gray24: string;
      gray25: string;
      gray26: string;
      gray27: string;
      dullGray: string;
      inputBackground: string;
      textGray: string;
      textGray2: string;
      textGray3: string;
      textGray4: string;
      textGray5: string;
      textGray6: string;
      blue: string;
      lightBlue: string;
      lightBlue2: string;
      lightBlue3: string;
      lightBlue4: string;
      lightBlue5: string;
      lightBlue6: string;
      darkBlue: string;
      blueCharcoal: string;
      errorBorder: string;
      errorBorder2: string;
      errorBackground: string;
      errorText: string;
      warningBackground: string;
      yellow1: string;
      alertInfoBackgroundColor: string;
      alertInfoBorderColor: string;
      brown: string;
      archivedColor: string;
      archivedBackground: string;
      activeColor: string;
      danger: string;
      dangerHover: string;
      alertInfo2BackgroundColor: string;
      alertInfo2BorderColor: string;
      alertInfo3BackgroundColor: string;
      alertInfo3BorderColor: string;
      tableEvenRowsBg: string;
      tableHeaderShadow: string;
      grayBorder: string;
      paleBlue: string;
      heavenly: string;
      creamyYellow: string;
      wetAsphalt: string;
      green1: string;
      green2: string;
      green3: string;
      green4: string;
      green5: string;
      green6: string;
      green7: string;
      green8: string;
      green9: string;
      green10: string;
      red1: string;
      red2: string;
      red3: string;
      underlineGray: string;
      picksEvenRowsBg: string;
      teamCardGreen: string;
      teamCardRed: string;
      teamCardGray: string;
      cream: string;
      cream2: string;
      wideBtnColor: string;
      tuna: string;
      brightGray: string;
      steelBlue: string;
      veryPaleBlue: string;
      emerald: string;
      cyan: string;
      gainsborough: string;
      sortBarColors: {
        clr0: string;
        clr1: string;
        clr2: string;
        clr3: string;
        clr4: string;
        clr5: string;
        clr6: string;
        clr7: string;
        clr8: string;
        clr9: string;
        clr10: string;
        clr11: string;
        clr12: string;
        clr13: string;
      };
      gridSelectGradient: {
        clr0: string;
        clr1: string;
      };
      sortBarColorsBright: {
        clr0: string;
        clr1: string;
        clr2: string;
        clr3: string;
        clr4: string;
        clr5: string;
        clr6: string;
        clr7: string;
        clr8: string;
        clr9: string;
      };
      lightGrayBorder: string;
      lightBlueBorder: string;
      skeletonBaseColor: string;
      transparentRgba: string;
      transparentHex: string;
      space: string;
      bgColorChartHeader: string;
      borderColorChartHeader: string;
      colorChart: string;
      skeleton: {
        baseColor1: string;
        highlightColor1: string;
      };
      lightActiveGray: string;
    };
    fonts: {
      Inter: string;
      Sohne: string;
      SegoeUI: string;
      CourierNew: string;
    };
    zIndex: {
      header: number;
      optionSelect: number;
      dropdown: number;
    };
    size: {
      account: {
        h1: string;
        h2: string;
        h3: string;
        h4: string;
      };
    };
  }
  export type LightTheme = {
    body: string;
    text: string;
  };
  export type DarkTheme = {
    body: string;
    text: string;
  };
}
